# dataset configurations
min_tempo: 135
sample_rate: 44_000
num_samples: 312888
split_after_beats: 16
verbose: true

offline_data_path: '/Users/anton/Documents/Music/Samoh/'
online_data_path: = 'none'

# model configurations
data_path: 'dataset/data/'