dataset:
  path: '/Users/anton/Documents/Music/'
  all_filetypes: true
  sample_rate: 44_000
  n_samples: 5
  hop_size: 8
  channels: 1
  split: [.8, .1, .1]
  batch_size: 16
  workers: 2
  shuffle: true
  limit: null

training:
  name: 'baseline_newdata'
  epochs: 100
  optimizer: 'adam'
  lr: 0.0001
  early_stop: 20
  clipping_fac: 2
  batch_size: 8

model:
  layers: 6
  stride: 2
  width: 128
  depth: 3
  codebook_dim: 64
  codebook_size: 512
  discard_vec_threshold: 1.0
  codebook_loss_weight : 0.8
  spectral_loss_weight: 1.0
  commit_loss_weight : 0.8
  init_random: true
  lstm: false