dataset:
  offline_data_path: '/Users/anton/Documents/Music/Samoh/'
  online_data_path: = 'none'
  min_tempo: 135
  sample_rate: 44_100
  num_samples: 312_000
  hop_size: 16
  verbose: true
  levels: 1

training:
  split: [.8, .1, .1]
  shuffle: true
  limit: None
  batch_size: 64
  epochs: 10
  lr: 0.005
  ckpt_name: 'best_vqvae_latent_2_codebook_5.pth'
  seed: 111
  output_train_dir: 'output'

model:
  channels: 1
  n_downsample: 4
  codebook_dim: 32
  codebook_size: 16
  depth: 4
  width: 8
  kenel_size: 2
  stride: 2
  discard_vec_threshold: 1
  reconstruction_loss_weight : 1
  codebook_loss_weight : 1
  commitment_loss_weight : 0.02
  codebook: "model/vqvae/params/codebook.tar"