dataset:
  offline_data_path: '/Users/anton/Documents/Music/'
  online_data_path: = 'none'
  min_tempo: 135
  sample_rate: 44_100
  num_samples: 352_800
  hop_size: 16
  verbose: true
  channels: 1
  split: [.8, .1, .1]
  batch_size: 64
  shuffle: true
  limit: None
  beat_split: false

training:
  name: 'base_model'
  epochs: 100
  optimizer: 'adam'
  lr: 0.005
  early_stop: 10

model:
  layers: 4
  kernel_size: 2
  stride: 2
  width: 8
  depth: 4
  codebook_dim: 32
  codebook_size: 16
  discard_vec_threshold: 1
  codebook_loss_weight : 0.5
  spectral_loss_weight: 1
  commit_loss_weight : 0.02
